apiVersion: apps/v1
kind: Deployment
metadata:
  name: wishlist-deployment
  labels:
    app: wishlist
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wishlist
  template:
    metadata:
      labels:
        app: wishlist
    spec:
      containers:
      - name: wishlist
        image: docker.io/aricentdocker/wishlist:5
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: wishlist
  labels:
    app: wishlist
spec:
  selector:
    app: wishlist
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
