apiVersion: apps/v1
kind: Deployment
metadata:
  name: shoes-deployment
  labels:
    app: shoes
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shoes
  template:
    metadata:
      labels:
        app: shoes
    spec:
      containers:
      - name: shoes
        image: docker.io/aricentdocker/shoes:1
        ports:
        - containerPort: 1002

---
apiVersion: v1
kind: Service
metadata:
  name: shoe
  labels:
    app: shoes
spec:
  selector:
    app: shoes
  ports:
    - protocol: TCP
      port: 1002
      targetPort: 1002
