apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart-deployment
  labels:
    app: cart
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cart
  template:
    metadata:
      labels:
        app: cart
    spec:
      containers:
      - name: cart
        image: docker.io/aricentdocker/cart:3
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: cart-service
  labels:
    app: cart
spec:
  type: LoadBalancer
  selector:
    app: cart
  ports:
    - protocol: TCP
      port: 80
      targetPort: 1004
      nodePort: 30010
