apiVersion: apps/v1
kind: Deployment
metadata:
  name: offers-deployment
  labels:
    app: offers
spec:
  replicas: 1
  selector:
    matchLabels:
      app: offers
  template:
    metadata:
      labels:
        app: offers
    spec:
      containers:
      - name: offers
        image: docker.io/aricentdocker/offers:3
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: offers-service
  labels:
    app: offers
spec:
  type: LoadBalancer
  selector:
    app: offers
  ports:
    - protocol: TCP
      port: 80
      targetPort: 1001
      nodePort: 30007
