apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui-deployment
  labels:
    app: ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ui
  template:
    metadata:
      labels:
        app: ui
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes-training
                operator: In
                values:
                - success
      containers:
      - name: ui
        image: docker.io/aricentdocker/ui:4
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: ui-web-service
  labels:
    app: ui
spec:
  type: LoadBalancer
  selector:
    app: ui
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
